# Generated by Django 6.0.1 on 2026-04-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
